ALTER TABLE "Settings" ADD COLUMN "tplOverdue" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Settings" ADD COLUMN "tplPending" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Settings" ADD COLUMN "tplExpiring" TEXT NOT NULL DEFAULT '';
